### PR TITLE
[FIX] web_widget_json_graph: Remove scss file

### PR DESCRIPTION
**Pull request by frahikLV**
@tomeyro

### CODE REVIEW

**Comment by luisg123v** [comment]
@frahikLV @tomeyro 

You have caused this branch to diverge by merging this PR. PRs should target the OCA repo instead.

Even if it was a temporary fix, a definitive PR should've been created. I advised @frahikLV to announce on https://github.com/OCA/web/issues/1388 he was going to migrate it.

CC @moylop260 @hbto

**Comment by luisg123v** [comment]
Sorry @frahikLV, but I had to undo this change as well as https://github.com/vauxoo/web/pull/25. We need to avoid divergences because of:
- It makes harder for us to keep repos updated with the original ones
- If someone else needs the repo, they will have to migrate it again (duplicated work)
- If it's on the OCA, both us and the community could apply or benefit from fixes

CC @hugho-ad

**Comment by hugho-ad** [comment]
@frahikLV 

Please added as a patch until you open the mr to OCA and get's merged

**Comment by luisg123v** [comment]
@hugho-ad,

@frahikLV is planning on adding this module [directly into the forecast repo](https://git.vauxoo.com/vauxoo/forecast/-/merge_requests/129). That's because it's the only repo that uses it, and it's not even migrated to v12 in the OCA, it was also merged for vauxoo:v12 on https://github.com/Vauxoo/web/pull/22.

What do you think?

**Comment by hugho-ad** [comment]
I would rather try to move it to OCA

**Comment by luisg123v** [comment]
I agree.

@frahikLV I merged the change in the forecast repo for now so we don't get stuck, but please add to your ToDo list creating the PR to the OCA for v12 & v13.

If you're too busy, I can help with that.

**Pull request merged**
