### PR TITLE
[10.0] Deprecate web_easy_switch_company

### PR DESCRIPTION
**Pull request by osvalr**
# Summary

In 10.0 there are modules that are enabled to be installable, in fact there are three of them which just one is not migrated to 10.0 (which one is being disabled in with this patch) and the others also appears to be not migrated yet but they doesn't generate errors.

## Deprecated: 
 - [x] `web_easy_switch_company`

### CODE REVIEW

**Comment by nhomar** [comment]
@osvalr 

Deprecate this module for v10 it is a feature in the core itself on v10

**Comment by osvalr** [comment]
@nhomar I'm making it uninstallable, how do I deprecate it?

**Comment by nhomar** [comment]
just delet it completelly and inform in the commit message it is deprecated in favor of "whatever the reason is"

**Comment by osvalr** [comment]
@nhomar thank you, I've removed the module

**Pull request merged**
